# Change these first
owner: fblacklight-organization # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Landing Page
    url: https://www.fblacklight.org/en
  - name: Registration
    url: https://registration.fblacklight.org
  - name: Apps Hub
    url: https://apps.fblacklight.org
  - name: Companion App
    url: https://companion.fblacklight.org
  - name: Authentication Service
    url: $SECRET_AUTH_SERVICES
    expectedStatusCodes:
      - 200
      - 404
  - name: Riddle Services
    url: $SECRET_RIDDLES_API
  - name: Virtual Queues
    url: $SECRET_VQ_SERVICE
  - name: Data Services
    url: $SECRET_DATA_SERVICES
  - name: Service Monitoring
    url: $SECRET_MONITORING_SERVICE


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fblacklight.org
  # baseUrl: /status
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Furry Blacklight Statuspage
  #introTitle: "We try to ensure that all our services are available 24/7"
  introMessage: "We try to ensure that all our services are available 24/7, if you encounter any issues even though the service is marked as live, please consider open a ticket in our Ticket System"
  navbar:
    - title: Status
      href: /
    - title: Tickets
      href: https://help.fblacklight.org

